# Generated by Django 5.1.7 on 2025-03-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0007_alter_incident_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='call_type',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], default='POST', max_length=4),
        ),
        migrations.AddField(
            model_name='datasource',
            name='call_type',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], default='GET', max_length=4),
        ),
        migrations.AddField(
            model_name='incident',
            name='state',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'In Progress'), (3, 'On Hold'), (4, 'Resolved'), (5, 'Closed/Canceled')], default=1),
        ),
    ]
