# Generated by Django 5.1.7 on 2025-03-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_app", "0008_automation_call_type_datasource_call_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="sys_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="state",
            field=models.IntegerField(
                choices=[
                    (1, "New"),
                    (2, "In Progress"),
                    (3, "On Hold"),
                    (4, "Resolved"),
                    (5, "Closed"),
                    (6, "Cancelled"),
                ],
                default=1,
            ),
        ),
    ]
