# Generated by Django 5.1.7 on 2025-03-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_app", "0009_incident_sys_id_alter_incident_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="priority",
            field=models.CharField(
                choices=[
                    ("1", "Critical"),
                    ("2", "High"),
                    ("3", "Medium"),
                    ("4", "Low"),
                    ("5", "Very Low"),
                ],
                default=5,
                max_length=20,
            ),
        ),
    ]
