# Generated by Django 5.1.7 on 2025-03-27 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_app", "0013_alter_incident_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="priority",
            field=models.CharField(
                choices=[
                    ("Critical", 1),
                    ("High", 2),
                    ("Medium", 3),
                    ("Low", 4),
                    ("Very Low", 5),
                ],
                default=5,
                max_length=20,
            ),
        ),
    ]
